using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace ExecuteProcess
{
    /// <summary>
    /// The form responsible for showing the output created by the CMD
    /// </summary>
    public partial class frResponse : Form
    {
        /// <summary>
        /// Initialize the form with the given text to be shown
        /// </summary>
        /// <param name="responseCMD">The Process.StandartOutput generated by executing a command on CMD</param>
        public frResponse(string responseCMD)
        {
            InitializeComponent();
            textBox1.Text = responseCMD;
        }
    }
}
